#配置服务器信息
server:
  port: 8082
spring:
  #mysql相关数据库设置
  datasource:
    url: jdbc:mysql://localhost:3306/mysqltest?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #mybatis依赖
mybatis:
  type-aliases-package: com.fdd.mybatis.dao